# Generated by Django 5.2.5 on 2025-09-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0002_usuariosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fabricante', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='novo', max_length=20)),
            ],
        ),
    ]
