# Generated by Django 5.2.5 on 2025-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0003_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='observacao_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='estado',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=20),
        ),
    ]
