# Generated by Django 5.2.5 on 2025-09-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0004_equipamento_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
