# Generated by Django 5.2.5 on 2025-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0005_colaborador_nome_usuario_colaborador_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome_usuario',
            field=models.CharField(default='none', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='senha',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
    ]
