# Generated by Django 5.2.5 on 2025-09-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0006_alter_colaborador_nome_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='colaboradores/'),
        ),
    ]
