# Generated by Django 5.2.5 on 2025-09-14 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0007_colaborador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_devolucao', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='emprestado', max_length=20)),
                ('observacao_devolucao', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='app_EPINav.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='app_EPINav.equipamento')),
            ],
        ),
    ]
