# Generated by Django 5.2.5 on 2025-09-20 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0008_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='status',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
