# Generated by Django 5.2.5 on 2025-09-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0009_remove_emprestimo_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='observacao_devolucao',
            new_name='observacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_devolucao',
        ),
    ]
