# Generated by Django 5.2.5 on 2025-09-26 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0010_rename_observacao_devolucao_equipamento_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='estado',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='fornecido', max_length=20),
        ),
    ]
