# Generated by Django 5.2.5 on 2025-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_EPINav', '0011_equipamento_quantidade_alter_emprestimo_data_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_efetiva_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
